### ISSUE TITLE
Error reading file, skipping: inflateReset: (null) (-2)

### ISSUE THREAD

**Issue by mxmlnkn** [vasi/lzopfs#5]
Happens to me with every gzip file. Is it related to [this](https://stackoverflow.com/questions/17820664/is-this-a-bug-in-this-gzip-inflate-method)?

**Comment by vasi** [comment]
Er, it turns out I was copying a z_stream, which you're apparently not allowed to do? Zlib now has a check that you're not doing this, so that makes things blow up.

Should be fixed now!
